In [5]:
import pandas as pd 


player_df = pd.read_csv("MLSPLAYEREXPORT.csv")

,Unnamed: 0,Player,Team,Season,Position,Minutes,Shots,SoT,G,xG,xPlace,G-xG,KeyP,A,xA,A-xA,xG+xA,PA,xPA
0,NaN,Hany Mukhtar,NSH,2022,ST,3082,126,65,23,21.01,-0.08,1.99,78,6,7.44,-1.44,28.45,8.78,12.14
1,NaN,Daniel Gazdag,PHI,2022,AM,3216,61,42,22,18.18,1.69,3.82,43,6,5.51,0.49,23.69,6.54,6.50
2,NaN,Taty Castellanos,NYC,2021,ST,2991,132,57,19,19.01,-0.57,-0.01,34,6,4.24,1.76,23.25,6.46,8.29
3,NaN,Luciano Acosta,CIN,2023,AM,2773,80,39,16,13.77,2.32,2.23,88,10,8.92,1.08,22.69,10.99,10.16
4,NaN,Cucho Hernández,CLB,2023,ST,2531,152,55,15,17.53,-2.66,-2.53,36,6,4.79,1.21,22.32,4.03,9.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2318,NaN,Antony Curic,TOR,2023,FB,3,0,0,0,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00
2319,NaN,Chris Rindov,SKC,2023,CB,13,0,0,0,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00
2320,NaN,Collin Smith,FCD,2023,FB,113,0,0,0,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00
2321,NaN,Jake Davis,SKC,2021,CM,3,0,0,0,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00
2322,NaN,Jake Davis,SKC,2022,CM,31,0,0,0,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00

In [49]:
player_df = pd.read_csv("MLSPLAYEREXPORT.csv")

exp_player=player_df.filter(['Season','Player','Team','Position','Minutes','Shots','SoT','G'])

exp_player.replace('\s+','-',regex=True,inplace=True)
exp_player['Player_ID']=exp_player['Player']+'-'+exp_player['Season'].astype(str)
exp_player['Count']=exp_player.groupby('Player_ID').cumcount()+1
exp_player['Player_ID'] += '-'+exp_player['Count'].astype(str)
exp_player
#exp_player.to_csv('player2.csv')

,Season,Player,Team,Position,Minutes,Shots,SoT,G,Player_ID,Count
0,2022,Hany-Mukhtar,NSH,ST,3082,126,65,23,Hany-Mukhtar-2022-1,1
1,2022,Daniel-Gazdag,PHI,AM,3216,61,42,22,Daniel-Gazdag-2022-1,1
2,2021,Taty-Castellanos,NYC,ST,2991,132,57,19,Taty-Castellanos-2021-1,1
3,2023,Luciano-Acosta,CIN,AM,2773,80,39,16,Luciano-Acosta-2023-1,1
4,2023,Cucho-Hernández,CLB,ST,2531,152,55,15,Cucho-Hernández-2023-1,1
...,...,...,...,...,...,...,...,...,...,...
2318,2023,Antony-Curic,TOR,FB,3,0,0,0,Antony-Curic-2023-1,1
2319,2023,Chris-Rindov,SKC,CB,13,0,0,0,Chris-Rindov-2023-1,1
2320,2023,Collin-Smith,FCD,FB,113,0,0,0,Collin-Smith-2023-1,1
2321,2021,Jake-Davis,SKC,CM,3,0,0,0,Jake-Davis-2021-1,1
2322,2022,Jake-Davis,SKC,CM,31,0,0,0,Jake-Davis-2022-1,1

In [32]:
teams_df= pd.read_csv('mlsteams21-23.csv')
teams_df= teams_df.filter(['Team','Season','Games','ShtF','ShtA','GF','GA','Pts'])

teams_df.to_csv('teams2.csv')

In [31]:
player_df = pd.read_csv('mlsgk21-23.csv')
exp_player=player_df.filter(['Season','Player','Team','Position','Minutes','Shots Faced','Goals Conceded','Saves'])

exp_player.replace('\s+','-',regex=True,inplace=True)
exp_player['Player_ID']=exp_player['Player']+'-'+exp_player['Season'].astype(str)
exp_player['Count']=exp_player.groupby('Player_ID').cumcount()+1
exp_player['Player_ID'] += '-'+exp_player['Count'].astype(str)
exp_player
exp_player.to_csv('player.csv')

In [36]:
games_df= pd.read_csv('mlsgamesraw.csv')

games_df=games_df.filter(['Date','Home','HG','Away','AG'])

games_df.to_csv('games2.csv')

In [61]:
passes_df = pd.read_csv('passraw.csv')

passes_df.replace('\s+','-',regex=True,inplace=True)
result_df = passes_df.merge(exp_player,on=['Team','Season','Player'],how='left')

export_df=result_df.filter(['Player_ID','Passes','Minutes','Distance','Vertical','Score','Season'])
export_df.to_csv('passes2.csv')

In [62]:
salaries_df=pd.read_csv('salariesraw.csv')


salaries_df.replace('\s+','-',regex=True,inplace=True)
result_df = salaries_df.merge(exp_player,on=['Team','Season','Player'],how='left')

export_df=result_df.filter(['Player_ID','Season','Base Salary','Guaranteed Compensation'])

export_df.to_csv('salaries2.csv')